### PR TITLE
make selected just orange dots

### PR DESCRIPTION
**Pull request by Hudik**
selected menu item makes orange just dot, not line

### CODE REVIEW

**Comment by timschoch** [comment]
Hello Andrew
Thanks for your work. I've checked your PR and there are several issues:
- the animation is missing. Here the link from the briefing: https://dribbble.com/shots/1676635-Page-scroll-concept
- the dots are not centered on the line anymore
- the dark line on the selected item should not go passed the orange dot (For me this was obvious, but I forgot to mention this.)
- this is a small one: the light gray dots of the lower navigation items is missing

I see how you used font-awesome to only color the dots - clever. But I can't see this approach work with the animation. How do you plan to tackle the animation?

**Comment by Hudik** [comment]
Hello, Tim.
  I didn't see KREATIVA example, but wanted to make animation with transform-scale property as well,  maybe not so natural as with TweenMax. Will take it as an example.
  p.2-3 - Ok, will fix this.
About lower navigation points: do you mean a points below selected item? If yes, should they be just points and without vertical grey line?

**Comment by timschoch** [comment]
Hi Andrew
you found a bug on the current page. It should look like this:
grafik

To answer your question over on freelancer.com: I don't really care how the animation is achieved, if it is the easiest with font awesome, go ahead. If you want to add another dom element and animate that, feel free to alter index.html. ;) And it doesn't have to look exactly like the one in the dribble. It should only show in dots and the transparent 1px lines of the background png. The dribble is more to show the organic feel of the animation I'm looking for. In the end it should feel like it's orange liquid that is forced through the dots and lines. It's a bit hard to explain in words, do you know how I mean?
Cheers, Tim

**Comment by Hudik** [comment]
Ok. I've managed to create an animation. Is it as you expected? If yes, I will add changes to make lower dots lighter.

**Comment by timschoch** [comment]
Sweet, I like the animation a lot!
Two hopefully minor issues:
- Can you make all dots the same size?
- The orange dot 'overshoots' a bit at the end of the animation and then bounces back. Can you reduce that a little, maybe to half the effect? I like that it does it, but currently its a bit too much.

**Comment by Hudik** [comment]
Made lower dots lighter and all dots with same size.
About orange dot 'overshoots': there is several possible pre-defined Eases in https://greensock.com/docs/#/HTML5/GSAP/TweenMax/TweenMax/. You may try to find the one which is most appropriate for you: just change property "ease" to one from a list given on TweenMax page in a line 18 of main.js:
  TweenMax.to($waterdrop,t,{y:dest,ease:Back.easeOut, yoyo:false})

Also, if you decide to alter items number in navigation, change "width" rule at line 67 of _navigation.scss:
   height: $navLineHeight * 5;
(where 5 = number of items - 1)

**Comment by timschoch** [comment]
Awesome, awesome, awesome! I'll do some minor clean up (like moving scss variables to main file and aligning the line etc) myself. I created a new target branch https://github.com/timschoch/portfolio/tree/orangedot for you.
Please change the target of your pull request to that branch and we're all done.

**Comment by timschoch** [comment]
Never mind, I found out that I can change the target branch myself ;)
thought only you could do that but nope, it worked...

**Pull request merged**
